### ISSUE TITLE
Make a push, folks!

### ISSUE THREAD

**Issue by afontaine** [IPPETAD/adventure.datetime#1]
We all have to make an edit and post by Monday at 4.

I'm looking for ways to make some new tags, but for now, this is what we got!

**Comment by Jtfinlay** [comment]
Done, it be... well, once Evan and Jesse hurry up.

**Comment by afontaine** [comment]
Closed! We can just make and assign issues for actual assignments and stuff during the project. What do you guys think?

**Comment by jviau** [comment]
That or wiki’s.

**Comment by Jtfinlay** [comment]
Yes.

**Comment by edegraff** [comment]
Should work well.
