### ISSUE TITLE
Last Minute Things

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#108]
It's due in ~~9 hours~~ 24 hours. Can we get these pull requests straightened away and finish the rest of the work? I'd rather not be up until midnight working on this.

Also, it would be best if we had some videos showing our app. We get an extra 2 marks for a Video Demo of our app, which we could also show at our presentation. I'd vote on @edegraff running the video off of his phone, since it's the most awesome. But we need everything squared away first.

**Comment by edegraff** [comment]
It's due in 24 hours, at 4 pm tomorrow.  We can use my phone for the video

**Comment by Jtfinlay** [comment]
Is that the time we are presenting?

**Comment by edegraff** [comment]
No, it's the time it's due in eclass.  I have no idea when we're presenting, did we ever sign up for a spot?

**Comment by Jtfinlay** [comment]
@afontaine said he was.. I dunno when he picked or whether he actually did.

**Comment by afontaine** [comment]
I emailed him for a Tuesday spot, but I haven't gotten a reply yet.

**Comment by jesseDtucker** [comment]
We'll get the video and presentation stuff sorted out tommorow as we aren't up until Wednesday. I'm expecting we'll do a demo video tonight and upload to YouTube for bonus marks. The refine it for Wednesday.

**Comment by Jtfinlay** [comment]
I think we completed this. I'll close it out.
