### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by edegraff** [IPPETAD/adventure.datetime#116]
The following error is coming up repeatedly with the new server changes:

12-02 21:34:12.213: E/StoryManager(3478): StoryManager: 
12-02 21:34:12.213: E/StoryManager(3478): java.lang.StringIndexOutOfBoundsException: length=0; regionStart=-2; regionLength=2
12-02 21:34:12.213: E/StoryManager(3478):   at java.lang.AbstractStringBuilder.startEndAndLength(AbstractStringBuilder.java:216)
12-02 21:34:12.213: E/StoryManager(3478):   at java.lang.AbstractStringBuilder.delete0(AbstractStringBuilder.java:244)
12-02 21:34:12.213: E/StoryManager(3478):   at java.lang.StringBuilder.delete(StringBuilder.java:343)
12-02 21:34:12.213: E/StoryManager(3478):   at ca.cmput301f13t03.adventure_datetime.model.WebStorage.getImages(WebStorage.java:320)
12-02 21:34:12.213: E/StoryManager(3478):   at ca.cmput301f13t03.adventure_datetime.model.WebStorage.mapImagesToFragment(WebStorage.java:517)
12-02 21:34:12.213: E/StoryManager(3478):   at ca.cmput301f13t03.adventure_datetime.model.WebStorage.getFragment(WebStorage.java:173)
12-02 21:34:12.213: E/StoryManager(3478):   at ca.cmput301f13t03.adventure_datetime.model.StoryManager$1.run(StoryManager.java:478)
12-02 21:34:12.213: E/StoryManager(3478):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-02 21:34:12.213: E/StoryManager(3478):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-02 21:34:12.213: E/StoryManager(3478):   at java.lang.Thread.run(Thread.java:841)

**Comment by Jtfinlay** [comment]
Pretty big issue. Thoughts, @jviau ?

**Comment by jviau** [comment]
I am pretty sure I have the fix already, I forgot to account for an empty list being passed into my method. It is a two line fix, should I just give it to one of you to quickly add to an existing pull request?

**Comment by edegraff** [comment]
Doesn't matter, just merge it in if you like.
