### ISSUE TITLE
Addressing Feedback

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#29]
Address any TA feedback on the previous project part.

**Comment by Jtfinlay** [comment]
Our awesomeness is documented [here](https://github.com/CMPUT301F13T03/adventure.datetime/wiki/Project-Part-2-Feedback). There were a few things noted that we should update / ask about.

Requirements Specification:
...
- Use case 1: server should also be an actor.
  There is no use case 100 or 104.
- Use case 3: Reader proceeds to interact with the story as in use case 1, use case 1 is browsing story(while expecting to be reading story)
- Use case test 4: number issue

Also, I would argue about the following:
- User should be able to download a story, edit it and publish it as his/her own.
- Users being able to get stories from other users and authors means they can somehow request stories from another user/author.

...

Glossary:
- Clear glossary but seems missing something, e.g. continue, browse, develop, choice.

Other than that we gone done good.

**Comment by afontaine** [comment]
Looks like @edegraff updated the glossary already. I fixed some stuff up, too. Closing.
