### ISSUE TITLE
Code Base of Prototype

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#30]
Your system will be demonstrated in the lab and its source code will be inspected. The code should conform to some consistent coding convention. At this point, your prototype should be implemented to provide something tangible to the user, supporting about half the requirements. Deliver the source code to your source repository.

**Comment by afontaine** [comment]
It looks like if we can have local storage + reading/creating up and running, we'll have a good enough prototype for the lab. Thoughts?

**Comment by edegraff** [comment]
Sounds like a solid prototype.  That would leave us with server, media, and comments to implement for the second part.

**Comment by afontaine** [comment]
We have a pull request in for server stuff! Think you guys can hook it up for 3?

**Comment by afontaine** [comment]
Released, closing.
