### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#32]
Provide JUnit test cases for your model classes and public methods. The interface to your model should be complete (and documented, above); however, the implementation need not be complete. Applying test-driven development, the test suite should test the entire interface of the model (not only the working part). Some tests will obviously fail because of incomplete functionality, and that is fine. Deliver the test code to your source repository. If you have test data files, also include those.

**Comment by afontaine** [comment]
I've begun writing tests for the DB, but @JTfinaly might need some help unit testing all those views. James, want to grab someone to help you write up some tests?

**Comment by edegraff** [comment]
It says we need test cases for "your model classes and public methods", do we need test cases for the views?

**Comment by Jtfinlay** [comment]
Good point. I'll talk to some other teams and see what they think. I think Isaac's still around.

I'd much rather not have to test the views. They seem to work from what I've done.

**Comment by afontaine** [comment]
Okay. We need someone writing tests for the web service and interfaces then (even if they fail for now)

**Comment by afontaine** [comment]
Test cases are under adventure.datetime
