### ISSUE TITLE
Object-Oriented Design

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#33]
Document your object-oriented design using a UML class diagram (or diagrams), including more detail on key attributes and methods. Include notes on the use of design patterns among the classes. The diagram(s) may be reverse engineered from the code, but must be edited, arranged, and selective (not a raw dump). The diagram(s) must be developed using eUML2, and embedded as image(s) in your team wiki. The diagram(s) will likely evolve.

**Comment by afontaine** [comment]
Has anyone looked at/updated our UML? Can we get someone on this?

**Comment by afontaine** [comment]
Closed as of #61
