### ISSUE TITLE
Release Planning

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#34]
Plan the major use cases and user stories that need to be done in the final two week period between the end of project part 3 and the end of project part 4 . (This plan can be done near the end of project part 3.) This plan will likely evolve and should be maintained up-to-date in your team wiki. It should be clear from the plan the progress towards satisfying all the specified requirements.

**Comment by afontaine** [comment]
Updated wiki. Can we now close?

**Comment by jviau** [comment]
Yup uhuh...wiki updated. Sure. Closed.
