### ISSUE TITLE
Reader Browses Stories on Server

### ISSUE THREAD

**Issue by afontaine** [IPPETAD/adventure.datetime#39]
[Use Case 4](https://github.com/CMPUT301F13T03/adventure.datetime/wiki/4-Reader-Browses-Stories-on-Server) is a more specific version of [Use Case 1](https://github.com/CMPUT301F13T03/adventure.datetime/wiki/1-Reader-Browses-Stories) that specifies that the stories are on the server. This must be implemented by Nov. 6.

**Comment by Jtfinlay** [comment]
I'd say this has been bug-lessly-ish completed as of #86
