### ISSUE TITLE
Requirements Specification

### ISSUE THREAD

**Issue by afontaine** [IPPETAD/adventure.datetime#4]
Describe, using detailed textual use cases, the tasks for completing each type of entry. For each user story in the project description, add a reasonable set of verifying tests. For easier reference (such as in planning), number the use cases and user stories. This information will likely evolve and should be maintained up-to-date in your team wiki. A "surprise" change will be introduced after project part 2.

**Comment by jesseDtucker** [comment]
This has a lot of overlap work with the release planning as they both require the user stories to be written.

**Comment by Jtfinlay** [comment]
What work has been done on this so far?

**Comment by jesseDtucker** [comment]
No idea. if you guys are working in ETLC I could swing by and help hammer some of this out. Just in NREF doing 379.

**Comment by afontaine** [comment]
Mostly just discussion really. Nothing concrete has been written down (I believe)

**Comment by afontaine** [comment]
Jacob and I have a midterm tomorrow morning. Could the other three get started on this today? We'll help out when we can today and definitely tomorrow.

**Comment by afontaine** [comment]
So it looks like we have all the use cases written up. According to the marking rubric, we need to have some planned tests. Once they're in the wiki, I think we're golden.

Release Planning also needs to be switched over to use the written use cases (I believe), but this should also be a quick switch.

**Comment by afontaine** [comment]
@jesseDtucker once you're done those test cases, comment here and close the issue please.

**Comment by jesseDtucker** [comment]
Test cases written. I'll meet up with you guys tomorrow and we can check for whatever is left. If anything.
