### ISSUE TITLE
Author Adds Fragment to Story

### ISSUE THREAD

**Issue by afontaine** [IPPETAD/adventure.datetime#41]
[Use Case 13](https://github.com/CMPUT301F13T03/adventure.datetime/wiki/13-Author-Adds-Fragment-to-Story) states that Authors can add Fragments to Stories. This must be implemented by Nov. 6.

**Comment by Jtfinlay** [comment]
Authors can now add fragments to the story as of #62 . 
Whether they can actually edit or view the fragment is questionable.

But technically we meet the specification.
