### ISSUE TITLE
Weekly Standup Meeting Time

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#47]
We discussed with the TA about moving our meeting time to sometime other than 5pm on Wednesday. 

What times would you all prefer? We can send whatever works between us to the TA and he can see what works.

Bonus points if it involves :rat: and :beer:

**Comment by jesseDtucker** [comment]
Wednesday I'm in the Lab from 2-5. Tuesday maybe? I think we're all free after 12:30.

**Comment by afontaine** [comment]
James and I have a lab from 2 to 5 every other Tuesday. What about Monday?

**Comment by jesseDtucker** [comment]
Monday works for me, I have practice at 6 and Evan, James and I have econ until 2.

**Comment by edegraff** [comment]
Yeah, Monday at 2 would be good.

**Comment by afontaine** [comment]
@Haiming247 how does Monday at 2 sound to you?
