### ISSUE TITLE
Object-Oriented Analysis

### ISSUE THREAD

**Issue by afontaine** [IPPETAD/adventure.datetime#6]
Document your initial object-oriented analysis using a UML class diagram (or diagrams), focusing on the most important anticipated classes, interfaces, and relationships. You may add attributes and methods if known. Add notes if the purpose of a class or interface is likely not clear to an outsider. The diagram(s) must be developed using eUML2 or drawn very nicely, and embedded as image(s) in your team wiki. The diagram(s) will likely evolve.

**Comment by afontaine** [comment]
I started the UML class diagram thus morning. It's under the branch 'UML' on my repo. It's by no means done, but it's a start.

**Comment by afontaine** [comment]
Due to the pulling of request #17, I think we can close this. @CMPUT301F13T03 thoughts?

**Comment by Jtfinlay** [comment]
I think it's good enough

**Comment by afontaine** [comment]
Cool. Closing. If anyone wants, they can reopen it.
