### ISSUE TITLE
Addressing feedback

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#68]
Address any TA feedback on the previous project part.
## Feedback

OOD:
- Add labels to patterns you used.

Test Cases:
- Comprehensive and runnable. The Story class constructor seems to be public to new an instance in one of the tests. Try to fix test errors.

Code Base of Prototype:
- Add Gson, android support lib and junit as internal lib.

**Comment by afontaine** [comment]
Feedback addressed ages ago.
