### ISSUE TITLE
Code Base of Prototype

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#69]
Your final system release will be demonstrated in the lab to evaluate the usability of its user interface and the degree to which its functionality fulfills the user's needs. Built-in help should be complete and consistent with the final user interface and functionality. The source code will be inspected. The code should conform to some consistent coding convention. Deliver the updated source code to your source repository.

**Comment by afontaine** [comment]
Code base all up and running. checkout tag [v1.0](https://github.com/CMPUT301F13T03/adventure.datetime/releases/tag/v1.0)
