### ISSUE TITLE
Release Planning

### ISSUE THREAD

**Issue by afontaine** [IPPETAD/adventure.datetime#7]
Plan the major use cases and user stories that need to be done in the two week period between the end of project part 2 ( Oct 23) and the end of project part 3 (Nov 6), and what will be deferred until later. (This plan can be done near the end of project part 2.) This plan will likely evolve and should be maintained up-to-date in your team wiki. This will be used to help track progress on completing the requirements.

**Comment by afontaine** [comment]
@CMPUT301F13T03/owners check and sign off on (or amend) [Release Planning](https://github.com/CMPUT301F13T03/adventure.datetime/wiki/Release-Planning) so we can close this. Remember, this is what has to be done by Nov. 6.

**Comment by jviau** [comment]
Edited it a bit. Some use cases left for next iteration were similar to ones on this iteration, so I moved them up.

**Comment by afontaine** [comment]
Looks good to me.

**Comment by edegraff** [comment]
Approved, let's close it.
