### ISSUE TITLE
Code Documentation

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#70]
For each source file, you should have a brief introductory comment describing its purpose or role within the application or a design pattern, as well as any currently outstanding issues. Provide Javadoc interface document for your model and basic command classes and their public methods (at least). Deliver the updated compiled Javadoc documentation to your source repository.

**Comment by afontaine** [comment]
All the javadoc is [here](https://github.com/CMPUT301F13T03/adventure.datetime/tree/master/doc/javadoc) and linked on the wiki.
