### ISSUE TITLE
Object-Oriented Design

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#73]
Document the structure of your object-oriented design using a UML class diagram (or diagrams), including detail on key attributes and methods. Include notes on the use of design patterns among the classes. The diagram(s) may be reverse engineered from the code, but must be edited, arranged, and selective (not a raw dump). As well, document the behavior of your design for a non-trivial scenario using a UML sequence diagram (e.g., something involving undo/redo and updating of multiple views). The diagrams must be developed using eUML2, and embedded as images in your team wiki.

**Comment by jviau** [comment]
I created a wiki page for design patterns.
https://github.com/CMPUT301F13T03/adventure.datetime/wiki/Design-Patterns

I also updated the UML class diagram for all of the Model classes, it is in my repo right now.

**Comment by jviau** [comment]
I think we will need James, Evan or Jesse, and Andrew or I to work on the UML sequence diagram together. That way we have someone that knows view, controller, and model present.

**Comment by afontaine** [comment]
UML is all updated and a bit segregated due to complexity. It is on the wiki.
