### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#74]
Run the JDeodorant tool for suggesting potential refactorings in your design. Implement the refactorings (as deemed reasonable), and describe the refactorings (done and not done) in a separate page in your team wiki.

**Comment by jviau** [comment]
I created the refactoring page:
https://github.com/CMPUT301F13T03/adventure.datetime/wiki/refactoring

**Comment by afontaine** [comment]
JDeoderant is only available as a stupid eclipse plugin soo... not running that.

**Comment by jesseDtucker** [comment]
I've got it setup, curious to see what it reports...

**Comment by jesseDtucker** [comment]
And... results are in. Apparently StoryFragment is a god class.... DeleteFragment is too long a method (14 or so lines) and our switch statements should be magically refactored into a state machine (they are not stateful switches).   Ya, so waste of time but now I have something to write about.

**Comment by afontaine** [comment]
Well... That was not where I was expecting a god class to be.
Interesting...

Oh, automated tools, always some kind of wrong...

**Comment by jesseDtucker** [comment]
Done, writeup in wiki
