### ISSUE TITLE
Glossary and Information Sources

### ISSUE THREAD

**Issue by afontaine** [IPPETAD/adventure.datetime#8]
Define any special terminology in the application domain (i.e., not programming terms). Provide a list of useful informational references or links to related or competitive products. Enter this information in your team wiki. Please clearly LICENSE your project.

**Comment by afontaine** [comment]
So... for the license, I'm thinking either MIT or GPL. Anybody else have anything?

**Comment by edegraff** [comment]
MIT would be good, or Apache is another option.  Jesse will not like GPL :)

**Comment by afontaine** [comment]
MIT is cool, I don't think we'll need patent protection :tongue:

**Comment by edegraff** [comment]
Sounds good!

**Comment by Jtfinlay** [comment]
Coolio

**Comment by afontaine** [comment]
@CMPUT301F13T03  take a look at [this](https://github.com/CMPUT301F13T03/adventure.datetime/wiki/Glossary-and-Index) so we can finish and close.

**Comment by edegraff** [comment]
Approved!

**Comment by jesseDtucker** [comment]
Approved. Added publish to definition list.
