### ISSUE TITLE
New Requirements

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#80]
Listed are the new requirements and the expectations. Which do we want to do? I've already implemented the ~ I'm feeling Lucky (small) ~ requirement. 

Thoughts?
# 

Expectation of new requirements

Customers make junk up all the time, it's up to you to decide what to handle.
Please document 5 NEW requirements (use-cases, OOA, OOD) and implement 2-3 of them. 3 is good if you have 3 small requirements. 2 Is good if you have a 1 small and 1 large requirements. Talk to your TA to make sure they approve the new requirements you have scheduled.
Implement 2-3 requirements, document 5.
# 

New requirements

== Random Choice (small) ==

As an author, I want to define that define a choice that will randomly
choose one of the possible links (like if there is path A, and path B
and then the choice "I'm feeling lucky" ala Google).

== Local Mirroring (medium) ==

As a user, I want to locally mirror the an entire story, including all
of its fragments and illustrations.

== Sync (Medium) ==

As an author, when I get back online I want to upload my fragments that
I made or edited.

== Versioning (Large) ==

As an author, I want each fragment versioned, when a user updates a
fragment the user has to send the old version number they changed, this
way if the fragment has changed the user will be notified of a conflict
and asked how to resolve the conflict. _UI_ _Network_

== Permissions (small) ==

As an author, I want to make some of fragments read only and their
illustrations read only.

== Multimedia (small) ==

As a user, I want to annotate fragments with audio or video.

As an author, I want the illustration to be an image or audio or video.

== Images (small) ==

As a author or user, when I add an illustration or an image I want the
option of resizing it to make it smaller.

== Fighting Fragments (Large) ==

As an author, I want to allow fragments to manipulate (increment,
decrement, min, max, multiply, divide) integer counters meant to
represent hit points or treasure (coins).

As an author, I want to define fighting fragments, specialized fragments
that have probabilistic games that manipulate a counter.

As an author, for a fighting fragment I want there to be thresholds
where if a counter gets too high or too low we transition to another
fragment.

As a user, I want to play the fighting fragments by choosing choices
that manipulate my counter states.

== I'm feeling Lucky (small) ==

As a user, I want a random story to be found and shown to me if I so ask.

**Comment by afontaine** [comment]
The other random one looks like it'll be fairly straight-forward to implement as well. I know @jesseDtucker really wants to do the fighting fragments, but I would think Local Mirroring or Sync wouldn't be too terrible either.

**Comment by jesseDtucker** [comment]
I have some other ideas too! I'm still bogged down with the TreeView right now so I can't start on them right away. Hopefully by the end of the week.

**Comment by Jtfinlay** [comment]
I could probably do the image cropping one without too much issue. How much image stuff do we have with the model? It would be nice to have a 'loadImageById(id:String):Bitmap' function.

Sync'ing authored stories was already sort of in the initial mock-up of the specifications, so that'll be straight forward enough.

**Comment by afontaine** [comment]
All done this.
