### ISSUE TITLE
Bookmarks on Reading Comments

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#95]
With recent additions, StartStory() automatically sets bookmark. Which is bad, I now realize. Because StartStory() is the only way for the view to set the current story, so using comments / storydescription / whatever now sets bookmarks.

@edegraff and myself will fix. This is a reminder to us.

**Comment by edegraff** [comment]
I've changed the bookmarks to now only be set when MakeChoice is called.  Also added deleting of the bookmark when the story is finished.  Changes are on my bookmarkshit branch, let me know what you think.
