### ISSUE TITLE
ReUpload as new story

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#99]
TODO:

Download story from server :+1:
Edit story :+1:
Change story author :-1:
Upload story as new story :-1:

**Comment by jviau** [comment]
The changing of the author and uploading as a now story will be done in Andrew's local dB flag. So long as you change the UUID of a story, it will upload as a new story.

**Comment by Jtfinlay** [comment]
Cool, I'll reassign to @edegraff and just note that it relies on #101

**Comment by afontaine** [comment]
Closed by #101
